
#include "grid_definition.h"

// Constant data (defined using the C interface, with the details generated by 'gen_grid.jl')
// The block grid topology is constant and can be omitted from the state vector to reduce verification time
// Defines 'BlockTopo' and 'ThreadWorkload'

c_code {
#include "grid_definition.c"
}

#if (TOTAL_BLOCKS >= REMOTE_BLOCK) || (TOTAL_BLOCKS >= NULL_BLOCK)
#  error "Too many blocks"
#elif (TOTAL_INTERFACES >= NULL_INTERFACE)
#  error "Too many interfaces"
#elif (TOTAL_REMOTE_BLOCKS >= REMOTE_BLOCK) || (TOTAL_REMOTE_BLOCKS >= NULL_BLOCK)
#  error "Too many remote blocks"
#endif

// C-side getters for the constant data

c_code {
    void c_get_neighbours(uchar block_idx, uchar sweep_num, uchar neighbour_idx[2], uchar interface_idx[2])
    {
        uchar offset = (sweep_num % DIMS) * DIMS;
        neighbour_idx[0] = grid_topology[block_idx].neighbours[0 + offset];
        neighbour_idx[1] = grid_topology[block_idx].neighbours[1 + offset];
        interface_idx[0] = grid_topology[block_idx].interfaces[0 + offset];
        interface_idx[1] = grid_topology[block_idx].interfaces[1 + offset];
    }

    uchar c_get_workload(uchar tid, uchar workload[MAX_WORKLOAD])
    {
        for (uchar i = 0; i < MAX_WORKLOAD; i++) {
            workload[i] = threads_workload[tid].blocks[i];
        }
        return threads_workload[tid].num_blocks;
    }
}

// Promela-side getters for the constant data

hidden byte _sweep_num;
hidden byte _block_idx;
hidden byte _neighbour_idx[2];
hidden byte _interface_idx[2];
inline get_topology(block, block_idx)
{
    d_step {
        _sweep_num = block.sweep_num;
        _block_idx = block_idx;
        c_code {
            c_get_neighbours(REF_HIDDEN(_block_idx), REF_HIDDEN(_sweep_num), REF_HIDDEN(_neighbour_idx), REF_HIDDEN(_interface_idx));
        }
        neighbour_idx[0] = _neighbour_idx[0];
        neighbour_idx[1] = _neighbour_idx[1];
        interface_idx[0] = _interface_idx[0];
        interface_idx[1] = _interface_idx[1];
    };
}

hidden byte _tid;
hidden byte _num_blocks;
hidden byte _workload[MAX_WORKLOAD];
hidden byte _iwl
inline get_workload(tid, num_blocks)
{
    d_step {
        _tid = tid;

        c_code {
            REF_HIDDEN(_num_blocks) = c_get_workload(REF_HIDDEN(_tid), REF_HIDDEN(_workload));
        }

        num_blocks = _num_blocks;
        for (_iwl : 0 .. MAX_WORKLOAD-1) {
            workload[_iwl] = _workload[_iwl];
        }
    }
}


// Mutable block grid data

mtype:BlockStates = { NewCycle, TimeStep, InitTimeStep, NewSweep, EOS, Exchange, Fluxes, CellUpdate, Remap, EndCycle };
mtype:BlockXChg   = { XCHG_NotReady, XCHG_InProgress, XCHG_Done };

typedef Block {
    mtype:BlockStates state;
    byte cycle;  // local cycle of the block
    byte sweep_num;
    bool must_wait;  // if the block is waiting for other blocks
};

typedef RemoteBlock {
    byte rank;
#if USE_MPI
    MPI_Request send_request;
    MPI_Request recv_request;
#endif
};

typedef BlockInterface {
    // in the Julia implementation, 'state' and 'flags' are stored in the same byte,
    // therefore atomic operations on both values at the same time is possible.
    mtype:BlockXChg state;
    byte flags;
    bool is_done[2];
};

// The block grid state is mutable and is part of the global state vector
Block block_grid[TOTAL_BLOCKS];
BlockInterface block_interfaces[TOTAL_INTERFACES];
RemoteBlock remote_blocks[TOTAL_REMOTE_BLOCKS];

mtype:TimeStepState = { DT_Ready, DT_AllContributed, DT_DoingMPI, DT_WaitingForMPI, DT_Done };
mtype:TimeStepState global_dt_state = DT_Ready;
byte dt_contributions = 0;  // number of blocks which contributed to the time step calculation for this cycle
byte global_cycle = 0;  // the current cycle of the whole solver


hidden byte _block_idx_disp;
inline print_block(block_index)
{
    d_step {
        // 'print_block' can be called from anywhere in the call stack of 'solver_async_cycle', as
        // 'block_index' is simply 'idx'
        _block_idx_disp = block_index;
        c_code {
            uchar idx = REF_HIDDEN(_block_idx_disp);
            Printf("Block{idx=%d, pos=(", idx);
            for (int pos_d = 0; pos_d < DIMS; pos_d++) {
                if (pos_d == 0) {
                    Printf("%d", grid_topology[idx].pos[pos_d]);
                } else {
                    Printf(", %d", grid_topology[idx].pos[pos_d]);
                }
            }
            Printf("), state=");
            printm(now.block_grid[idx].state, "BlockStates");
            Printf(", cycle=%d, sweep=%d, wait=%d}",
                now.block_grid[idx].cycle, now.block_grid[idx].sweep_num, now.block_grid[idx].must_wait);
        }
    }
}
