## Swarm Version 3.2 -- 5 June 2017
#
# Default Swarm configuration file
#
# there are four main parts to this configuration file:
#	ranges, limits, compilation options, and runtime options
# the default settings for each are shown below -- edit as needed
# comments start with a # symbol
# This version of swarm requires Spin Version 5.2 or later

# See the documentation for the additional use of
# environment variables CCOMMON, RCOMMON, and SCOMMON
# http://spinroot.com/swarm/

# range
k	1	4	# optional: to restrict min and max nr of hash functions

# limits
d	1000000	# optional: to restrict the max search depth
cpus	32 	# nr available cpus (exact)
memory	8G		# max memory per run; M=megabytes, G=gigabytes
time	64h		# max time for all runs; h=hours, m=min, s=sec, d=days
hash	1.5		# hash-factor (estimate)
vector	430 	# nr of bytes per state (estimate)
speed	500000		# nr states explored per second (estimate)
file	main.pml	# file with the spin model to be verified

# compilation options (each line defines one complete search mode)
# each option currently must include -DBITSTATE and -DPUTPID

-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC		# basic dfs
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DREVERSE	# reversed process ordering
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DT_REVERSE	# reversed transition ordering
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DREVERSE -DT_REVERSE	# both
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DP_RAND -DT_RAND	# same series with randomization
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DP_RAND -DT_RAND -DT_REVERSE
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DP_RAND -DT_RAND -DREVERSE
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DP_RAND -DT_RAND -DREVERSE -DT_REVERSE
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DBCS	# with bounded context switching
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DBCS -DREVERSE
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DBCS -DT_REVERSE
-DBITSTATE -DPUTPID -DVECTORSZ=2048 -DCONSERVATIVE=2 -DSC -DBCS -DREVERSE -DT_REVERSE

# runtime options (one line)
-c10 -x -n

# spin options other than -a (one line)
